version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /index\.html$
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  script: tinysells.app